countries = ['US', 'India', 'Brazil', 'France', 'Turkey', 
'Russia', 'United Kingdom', 'Italy', 'Argentina', 'Germany', 
'Spain', 'Colombia', 'Iran', 'Poland', 'Mexico', 'Ukraine', 'Peru', 
'Indonesia', 'South Africa', 'Netherlands', 'Czechia', 'Chile', 'Canada', 
'Philippines', 'Iraq', 'Romania', 'Sweden', 'Belgium', 'Pakistan', 'Portugal', 
'Israel', 'Bangladesh', 'Hungary', 'Japan', 'Jordan', 'Serbia', 'Switzerland', 
'Austria', 'Malaysia', 'Nepal', 'United Arab Emirates', 'Lebanon', 'Morocco', 
'Saudi Arabia', 'Kazakhstan', 'Ecuador', 'Bulgaria', 'Greece', 'Belarus', 
'Slovakia', 'Bolivia', 'Panama', 'Paraguay', 'Croatia', 'Tunisia', 'Georgia', 
'Azerbaijan', 'Costa Rica', 'Kuwait', 'Uruguay', 'West Bank and Gaza', 
'Dominican Republic', 'Denmark', 'Lithuania', 'Ethiopia', 'Egypt', 'Ireland',
 'Guatemala', 'Moldova', 'Slovenia', 'Bahrain', 'Honduras', 'Venezuela', 'Oman', 
 'Armenia', 'Qatar', 'Bosnia and Herzegovina', 'Sri Lanka', 'Libya', 'Thailand', 
 'Kenya', 'Nigeria', 'North Macedonia', 'Cuba', 'Burma', 'Korea, South', 'Latvia', 
 'Albania', 'Algeria', 'Estonia', 'Norway', 'Kosovo', 'Kyrgyzstan', 'China', 
 'Uzbekistan', 'Zambia', 'Montenegro', 'Ghana', 'Finland', 'Cameroon', 'Afghanistan', 
 'El Salvador', 'Cyprus', 'Mozambique', 'Luxembourg', 'Maldives', 'Mongolia', 
 'Singapore', 'Namibia', 'Botswana', 'Uganda', 'Jamaica', "Cote d'Ivoire", 'Madagascar', 
 'Senegal', 'Zimbabwe', 'Sudan', 'Angola', 'Malawi', 'Cambodia', 'Congo (Kinshasa)', 
 'Cabo Verde', 'Malta', 'Australia', 'Rwanda', 'Trinidad and Tobago', 'Syria', 'Gabon', 
 'Guinea', 'Mauritania', 'Eswatini', 'Guyana', 'Papua New Guinea', 'Suriname', 'Haiti',
  'Somalia', 'Mali', 'Andorra', 'Togo', 'Burkina Faso', 'Tajikistan', 'Belize', 
  'Seychelles', 'Bahamas', 'Congo (Brazzaville)', 'Djibouti', 'Taiwan*', 'Lesotho', 
  'South Sudan', 'Vietnam', 'Equatorial Guinea', 'Benin', 'Timor-Leste', 'Nicaragua', 
  'Central African Republic', 'Yemen', 'Iceland', 'Gambia', 'Niger', 'Saint Lucia', 
  'San Marino', 'Chad', 'Burundi', 'Eritrea', 'Sierra Leone', 'Barbados', 'Comoros', 
  'Guinea-Bissau', 'Liechtenstein', 'New Zealand', 'Monaco', 'Sao Tome and Principe', 
  'Liberia', 'Saint Vincent and the Grenadines', 'Laos', 'Bhutan', 'Mauritius', 
  'Antigua and Barbuda', 'Diamond Princess', 'Fiji', 'Tanzania', 
  'Brunei', 'Dominica', 'Grenada', 'Saint Kitts and Nevis', 'Holy See', 'Solomon Islands', 'MS Zaandam', 'Marshall Islands', 'Vanuatu', 'Samoa', 'Kiribati', 'Micronesia']